# Site settings
title: Not Enough Practice
email:
description: > # this means to ignore newlines until "baseurl:"
  A blog dedicated to helping people interested in Security and Forensics to practice and hone their skills outside a classroom. Building a community of like-minded geeks.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://notenoughpractice.com" # the base hostname & protocol for your site
twitter_username: GetPracticing
github_username:

# Build settings
markdown: kramdown
