# Site wide configuration

title: Not Enough Practice
description: "Not Enough Practice - We put our knowledge of Security and Forensics to the test!"
logo: Logo2.png
teaser: Logo4.png
locale:
url: /

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Kate Slaughter
  email: notenoughpractice@gmail.com
  twitter: startpracticing
  google:
    ad-client: 
    ad-slot: 
  bio: 
  avatar: Logo2.png
disqus-shortname: notenoughpractice


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
